#ifndef	__SIPPROTOCOL_HPP__
#define	__SIPPROTOCOL_HPP__

// Answers
#define	SIP_HELLO "HELLO"
#define	SIP_RESP "RESP"
#define	SIP_CONTACT "CONTACT"
#define SIP_CALL_REQUEST "CALL"
#define	SIP_CONTACT_IP "CONTACT_IP"
#define SIP_DECLINED "DECLINED_CALL"
#define	SIP_MESSAGE "MESSAGE"
#define	SIP_SUCCESS "200"
#define	SIP_UNAUTHORIZED "403"
#define	SIP_NOTFOUND "404"
#define	SIP_ALREADYCONNECTED "405"

// Requests
#define	SIP_CREATE_ACCOUNT "CREATE_ACCOUNT"
#define	SIP_CONNECT "CONNECT"
#define	SIP_SET_STATUS "SET_STATUS"
#define	SIP_LIST_CONTACTS "LIST_CONTACTS"
#define	SIP_ADD_CONTACT "ADD_CONTACT"
#define	SIP_DELETE_CONTACT "DELETE_CONTACT"
#define	SIP_CALL "CALL"
#define SIP_ACCEPT_CALL "ACCEPT_CALL"
#define SIP_DECLINE_CALL "DECLINE_CALL"
#define	SIP_SEND_MESSAGE "SEND_MESSAGE"
#define	SIP_GET_MESSAGES "GET_MESSAGES"

#endif /* __SIPPROTOCOL_HPP__ */
